# Generated by Django 5.2.1 on 2025-05-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attorney', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attorneyemail',
            options={'verbose_name': 'Attorney Email', 'verbose_name_plural': 'Attorney Emails'},
        ),
        migrations.AlterModelOptions(
            name='emailerrorlog',
            options={'verbose_name': 'EmailErrorLog', 'verbose_name_plural': 'Email Error Logs'},
        ),
    ]
